# File: .github/workflows/azcli.yaml

on:  
  workflow_dispatch:
    inputs:
      actions:
        description: 'Action to be performed'
        required: true
        type: choice
        options:
          - Deploy
          - Delete

name: AzureCLIDeployment

jobs:
  DockerImageBuild:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.actions == 'Deploy' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker image build
      run: docker-compose up -d
    - name: Docker Tag & Push 
      run: |
            docker image tag greenflux-assignment_dns accts324/greenflux_dnsmasq:1.0
            docker push accts324/greenflux_dnsmasq:1.0
            

  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.actions == 'Deploy' }}
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/greenflux.sh
          $GITHUB_WORKSPACE/greenflux.sh
  delete:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.actions == 'Delete' }}
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
             echo "Deleting all resources"
             az group delete --name greenflux-virtual-network-rg -y